#!/usr/bin/env bash
set -e
# gif2go - Generate asciigif frameset .go file from a GIF file
# Usage:  gif2go [-o DIR] [-n NAME] [-b 2|8|24] [-w WIDTH] FILE.gif
# Required:  jp2a imagemagick(convert)

# Default values
framesdir=frames
colorbits=2
width=64

Usage(){ # 1:message
	echo "gif2go - Generate asciigif frameset .go file from a GIF file"
	echo "Usage:  gif2go [-o DIR] [-n NAME] [-w WIDTH] [-b 2|8|24] FILE.gif"
	echo "  DIR:    Directory with your frameset .go files (with frames.go in it)"
	echo "  NAME:   The name that you use to invoke it, like: curl localhost:8080/NAME"
	echo "  WIDTH:  Width in characters of the frameset"
	echo "  The '-b' color bit depth can be 2 (b/w), 8, or 24 (\"true\" color)"
	echo "  The -FLAGs must be given before the filename!"
	[[ $1 ]] &&
		echo -e "\n$1"
	exit
}

framesfile=$framesdir/frames.go
[[ ! -f $framesfile ]] &&
	echo "### Framesfile $framesfile must exist in '$framesdir' already" &&
	exit 1

# Check arguments
((!$#)) &&
	Usage "### Must have at least a .gif filename as an argument"

# Get options
file= name=
while getopts ":ho:n:b:w:" opt
do
	case $opt in
	o) framesdir=$OPTARG ;;
	b) colorbits=$OPTARG ;;
	n)
		[[ $OPTARG =~ ^[a-zA-Z0-9_]+$ ]] &&
			name=$OPTARG &&
			continue
		echo "### Not a alphanumeric+underscore name: $OPTARG"
		exit 1 ;;
	w)
		((OPTARG>0)) &&
			width=$OPTARG &&
			continue
		echo "## Not a positive integer for width: $OPTARG"
		exit 1 ;;
	h) Usage ;;
	\?) Usage "### Unknown flag: -$OPTARG" ;;
	*) Usage "### Unknown argument: $OPTARG"
  esac
done
shift $((OPTIND -1))

# Check input file
file=$1
[[ ! -f $file ]] &&
	echo "### File not found: $file" &&
	exit 1

! file "$file" |grep -q GIF &&
	echo "### File not a .gif file: $file" &&
  exit 1

[[ ! $colorbits = 2 && ! $colorbits = 8 && ! $colorbits = 24 ]] &&
	echo "### Color bit depth can only be 2, 8 or 24, not '$colorbits'" &&
	exit 1

# Get frameset name
[[ -z $name && ! $file =~ ^-.* ]] &&
	name=$(basename "$file" .gif) name=${name//[^a-zA-Z0-9_]} name=${name,,}
outfile=$framesdir/$name.go
[[ -f $outfile ]] &&
	echo "### Frameset file already exists: $outfile" &&
	exit 1

# Set up output directory
mkdir -p "$framesdir/$name"
rm -f "$framesdir/$name"/*

# Generate PNG frames
convert -coalesce "$file" "$framesdir/$name/f%03d.png"

# Generate ANSI frames into go file
out="package frames\n\nfunc init() {\n\tFrameMap[\"$name\"] = DefaultFrameType(_$name)\n}\n\nvar _$name = []string{\n"
for f in "$framesdir/$name"/f*.png
do
	out+="\t\`"
	out+=$(jp2a --colors --color-depth=$colorbits --background=dark --width=$width "$f" |sed 's/ *$//')
	out=${out:0: -1}"\`,\n\n"
done
out=${out:0: -2}"}"
echo -e "$out" >"$outfile"
rm -rf -- "$framesdir/$name"
echo "=== Done: $outfile"

exit 0
