#!/usr/bin/env bash
set -e
# gif2go - Generate asciigif frameset .go file from a GIF file
# Usage:  gif2go [-o DIR] [-n NAME] [-b 2|8|24] [-h HEIGHT] FILE.gif
# Required:  jp2a imagemagick(convert)

# Default values
framesdir=frames
colors=2
height=24
bg=dark
force=0

Usage(){ # 1:message
	cat <<-EOH
		gif2go - Generate asciigif frameset .go file from a GIF file
		Usage:  gif2go [-o DIR] [-n NAME] [-w WIDTH] [-c 2|4|8|24] [-l] [-f] FILE.gif
		  DIR:     Directory with frames.go  and frameset files (default: frames)
		  NAME:    Name used to invoke it, like: curl localhost:8080/NAME
		  HEIGHT:  Heighth in characters of the frameset (default: 24)
	    -c:      Colors:  2: B/W,  4: ANSI,  8: 256bit,  24: truecolor (default: 2)
	    -l:      Light background (default: dark)
	    -f:      Force writing the output file, overwriting any present file
	  The -FLAGs must be given before the filename!
	EOH
	[[ $1 ]] &&
		echo -e "\n$1"
	exit
}

framesfile=$framesdir/frames.go
[[ ! -f $framesfile ]] &&
	echo "### Framesfile $framesfile must exist in '$framesdir' already" &&
	exit 1

# Check arguments
((!$#)) &&
	Usage "### Must have at least a .gif filename as an argument"

# Get options
file= name=
while getopts ":lfo:n:c:h:" opt
do
	case $opt in
	l) bg=light ;;
	f) force=1 ;;
	o) framesdir=$OPTARG ;;
	c) colors=$OPTARG ;;
	n)
		[[ $OPTARG =~ ^[a-zA-Z0-9_]+$ ]] &&
			name=$OPTARG &&
			continue
		echo "### Not a alphanumeric+underscore name: $OPTARG"
		exit 1 ;;
	h)
		((OPTARG>0)) &&
			height=$OPTARG &&
			continue
		echo "## Not a positive integer for width: $OPTARG"
		exit 1 ;;
	\?) Usage "### Unknown flag: -$OPTARG" ;;
	*) Usage "### Unknown argument: $OPTARG"
  esac
done
shift $((OPTIND -1))

# Check input file
file=$1
[[ ! -f $file ]] &&
	echo "### File not found: $file" &&
	exit 1

! file "$file" |grep -q GIF &&
	echo "### File not a .gif file: $file" &&
  exit 1

[[ ! $colors = 2 && ! $colors = 4 && ! $colors = 8 && ! $colors = 24 ]] &&
	echo "### Colors not 2 / 4 / 8 /24" &&
	exit 1

# Get frameset name
[[ -z $name && ! $file =~ ^-.* ]] &&
	name=$(basename "$file" .gif) name=${name//[^a-zA-Z0-9_]} name=${name,,}
outfile=$framesdir/$name.go
if [[ -f $outfile ]]
then
	((!force)) &&
		echo "### Frameset file already exists: $outfile" &&
		exit 1
	echo "--- Overwriting existing frameset file: $outfile"
fi

# Set up output directory
mkdir -p "$framesdir/$name"
rm -f "$framesdir/$name"/*

# Generate PNG frames
convert -coalesce "$file" "$framesdir/$name/f%03d.png"

# Generate ANSI frames into go file
out="package frames\n\nfunc init() {\n\tFrameMap[\"$name\"] = DefaultFrameType(_$name)\n}\n\nvar _$name = []string{\n"
for f in "$framesdir/$name"/f*.png
do
	out+="\t\`"
	out+=$(jp2a --color-depth=$colors --background=$bg --height=$height "$f" |sed -e 's/ *$//' -e 's/ *`,/`,/')
	out=${out:0: -1}"\`,\n\n"
done
out=${out:0: -2}"}"
echo -e "$out" >"$outfile"
rm -rf -- "$framesdir/$name"
echo "=== Done: $outfile"

exit 0
