package frames

func init() {
	FrameMap["friskdance"] = DefaultFrameType(_friskdance)
}

var _friskdance = []string{
	`
              ..........
          .................
         ....................
       .......................
      ...........,,,....,lO:,.
     ..........,;KKKo;;cXOddd...
    ...........OXlcckKKXXx:::c;.
    ......cd.,d0XoooOKKXXXKXXXd..
    ......kX;cXXXKKXXXo;;dX00:cxxx.
    ......dO0KKKKKXKKK0OxkO;'.:0Ok.
     .......ldddddxKKXkl..,:c;,;..
   ;ool.....',,,,..ccc'.,''''.
   lKK0:::;:ccccc::::;::c,...
    .:::;;;;;,.:ccccccccc::'.
            ..':ccccccccccccc.
             'ccccccccccccccc.
             .ccccccc:ccccccc.
             .:cccccccccccc,'.
            ...:ccccccccccccc.
           .:cccc,,;;,:cccccc.
           .'''''    .'',,',,.
            .....    ......
           ....        .....`,

	`


            ............
       ....................
       ......................
      .........,;.......;'...
     ........'l0Xlcl'.;oXl...
    .........:XXXXXXkoOO;'....
    ......ox,';OK:;;xXK0dxx......
    ......kX0d'OX000OkkOXKX'.k00l.
   .::;...ldKKKKXKXXo;;cXOd,'xxd;
   lKK0,....:ccccKKKd:ccc;,ccc,.
   .,,;cc;:::::..,,,..,,.,ccc..
    .,,;:ccc::c:::::::::.....
        .;;;..cc:cccccccc,.
          ..';ccccccccccc;'.
           .:cccccccccccccc..
           .,:ccccccccccccc..
            .,ccccccccccccccc.
           .:cccccccccccccccc.
           .:ccccc:,'':cccc,'
            .''''..  ..''''
           ......    .......`,

	`



        ...............
     ....................
     ......................
    ........:;......;l'....
   .......co0Oo....oOXkl....
   .......kX000kxxxK0OOx.....
   ....'''OX;''OXXKXl'';Kl...
   ....okKKXKKKKKoookKKKXl...;::'.
    ....'cOKKKKKXlllkKK0c,.,,OKKl.
  ........',,,,OKK0,,,,,:::cc,',.
 .kOk.......;;.,;;,.,:::c:;..
  dxd..c:'..:cccccccccccc,.
  ...,,ccc..;c:cccccccccc;,.
     .''''..:cccccccccccccc..
           .,::cccccccccccc'.
            ...:ccccccccccccc.
            .,ccccccccccccccc.
           .:ccccccc;,',ccc,'
            .''''.......'''
           ......    .......`,

	`
              .............
           ....................
         ........................
       ...........................
       ...''xo,....k:.''...........
       ...kKKKKc;;:Ko;kk............
      ..'ccccdXKKXXXKKKk...:l.......
     ...cXdooxXKK;;;xXX0o;.OX.......
    ....:0KXKKOOOdddOXXXXOxO0......
   l00k...dOKx'''KXKXXXXXXX,..:K00.
   ;ddo'''..odoooKKXkdddddd..':kxd
       ';c;,..,..ccc'.',,..',c;'.
       ......'c::;;::::cc::cc..
           .;:ccccccccccccc'.
          .':cccccccccccc;,.
         .;cccccccccccccc;,.
         .;cccccccccccc:ccc..
          .':cccccccccccc;'..
         .;cccccccccccccccc..
         .;cccccc;,,:cccccc..
         .'':cccc.. .':cccc..
            .'''..   ..''''
           ....        .....`,

	`
              .............
           ....................
         ........................
       ...........................
       ...''xo,....k:.''...........
       ...kKKKKc;;:Ko;kk............
      ..'ccccdXKKXXXKKKk...:l.......
     ...cXdooxXKK;;;xXX0o;.OX.......
    ....:0KXKKOOOdddOXXXXOxO0......
   l00k...dOKx'''KXKXXXXXXX,..:K00.
   ;ddo'''..odoooKKXkdddddd...:kxd
       ';c;,..,..ccc'.',,..',:;'.
       ......'c::;;::::cc::cc..
           .;:ccccccccccccc'.
          .':cccccccccccc;,.
         .;cccccccccccccc;,.
         .;cccccccccccc:ccc..
          .':cccccccccccc;'..
         .;cccccccccccccccc..
         .;cccccc;,,:cccccc..
         .'':cccc.. .':cccc..
            .'''..   ..''''
           ....        .....`,

	`

              .............
          .....................
         ........................
       .....'....,'...............
       ...,;Ok;..KO.';..............
       ...kXXXKocK0lkX:.............
     ...,d:;;oXKKXXXXKkl...........
  .:xxd.cXxddkXKK:;;xXKO...oxxc....
   cOOx.:OKKX0kkk000KKKK0o.OXOl.....
    ...c;'odKk;;;KKXKKKKKKKxd...'::;
       ',c;,:ccccclKKKdcccc....,oKKO.
         .;c::::;..,,;.....;:;:c;,,.
          ..:cccc::::::::::;;:'..
          .':cccccccc:ccc:;..
         .;cccccccccccccc,.
         .;cccccccccccccc,.
         .;cccccccccccccc,.
         .:cccccccccccccc,.
       .'cccccccccccccccc;'
       .'cccccc,',,':cccccc..
         .'''''..   .''''''
           ......    .......`,

	`


              .............
            ....................
         .........................
         ...,'....................
         ...OOc....c'...............
       .....OXXxoodK:.:l...........
       ...oxO0OKXXXXkokOx:.........
  ..'''...kX;''OXXXXl'';XK0;'Oo.....
  .lKKO'..kXKKKdoodKKKKKXXXKKx:.....
   ,cddc:,:c0KKocloKKXKKKx:cc.......
     ..ccc:;,,,,,0KKKKl,,'......:kkd.
       ..:..;::'.,;;;;'..,:'..,:oOko
          ..;cccccccccccc:;ccccc:;
          .,:ccccccccccc:,.',,,,.
         .;cccccccccccccc,.
         .;cccccccccccccc,.
         .:cccccccccccccc,.
       .'cccccccccccccccc;'
       .'cccc:'''',cccccccc..
         .'''.......'''''''
           ......    .......`,
}
